import Head from "next/head";
import styles from "./Home.module.css";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { loginThunk } from "../store/loginSlice";
import { useState } from "react";

export default function Home() {
  const [username, setUsername] = useState();
  const [password, setPassword] = useState();
  const dispatch = useDispatch();
  const loginSliceData = useSelector((state) => state.loginSlice);
  const status = loginSliceData.status;
  const router = useRouter();

  const onSubmitHandler = (e) => {
    e.preventDefault();
    const user = {
      username: username,
      password: password,
    };
    dispatch(loginThunk(user));
    if (status === "success") {
      router.push("/expenses");
    }
  };

  useEffect(() => {
    if (localStorage.getItem("username")) {
      localStorage.setItem("loginSuccess", true);
      router.push("/expenses");
    } else localStorage.setItem("loginSuccess", false);
  }, []);

  return (
    <>
      <Head>
        <title>Expense tracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={onSubmitHandler}>
          <label htmlFor="username">Username</label>
          <input type="text" onChange={(e) => setUsername(e.target.value)} />
          <label htmlFor="password">Password</label>
          <input type="text" onChange={(e) => setPassword(e.target.value)} />
          <button type="submit">Login</button>
        </form>
      </main>
    </>
  );
}
